#: Scrollback and Selection {{{

#: Copy output of the last command directly to clipboard
map ctrl+shift+s launch --stdin-source=@last_cmd_output xsel --clipboard --input

#: Copy entire screen + scrollback to clipboard
map ctrl+shift+a launch --stdin-source=@screen_scrollback xsel --clipboard --input

#: Open scrollback buffer in pager
map ctrl+shift+h show_scrollback

#: Scroll to previous command (larger jumps)
map ctrl+page_up scroll_page_up

#: Scroll to next command (larger jumps)
map ctrl+page_down scroll_page_down

#: Scroll up line by line
map ctrl+up scroll_line_up

#: Scroll down line by line
map ctrl+down scroll_line_down

#: }}}

#: Other mappings {{{

# Delete next word
map alt+delete send_text all \x1bd

#: }}}
